#!/usr/bin/env bash
# One-command connected experience for a fresh clone.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
PORT="${PORT:-4174}"
HOST="${HOST:-127.0.0.1}"
MODE="${1:---connected}"
PUBLIC_ORIGIN="${RESUME_AGENT_PUBLIC_ORIGIN:-https://resume.flowsome.top}"
FRONTEND_CONFIG="$ROOT/supabase-config.js"
WORKER_CONFIG="$ROOT/supabase-config.worker.js"
GENERATED_RUNTIME_CONFIG=0

if ! command -v python3 >/dev/null 2>&1; then
  echo "未找到 Python 3。请先安装 Python 3，然后重新运行 ./start.sh。"
  exit 1
fi

cleanup() {
  if [[ "$GENERATED_RUNTIME_CONFIG" == "1" ]]; then
    rm -f "$FRONTEND_CONFIG" "$WORKER_CONFIG"
  fi
}
trap cleanup EXIT

download_public_config() {
  local source_url="$PUBLIC_ORIGIN/supabase-config.js"
  local temporary_config
  temporary_config="$(mktemp)"
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL --max-time 20 "$source_url" -o "$temporary_config"
  else
    python3 - "$source_url" "$temporary_config" <<'PY'
import sys
from urllib.request import urlopen

source, target = sys.argv[1:]
with urlopen(source, timeout=20) as response, open(target, "wb") as output:
    output.write(response.read())
PY
  fi
  if ! grep -q 'anonKey' "$temporary_config" || ! grep -q 'workspaceId' "$temporary_config"; then
    rm -f "$temporary_config"
    echo "公开体验配置无效，请稍后重试或运行 ./dev.sh --demo。"
    exit 1
  fi
  GENERATED_RUNTIME_CONFIG=1
  {
    echo "// Resume Agent public cloud runtime; generated by start.sh."
    sed '/^\/\/ Generated at deploy time/d' "$temporary_config"
  } > "$FRONTEND_CONFIG"
  rm -f "$temporary_config"
  cat > "$WORKER_CONFIG" <<EOF
// Resume Agent public cloud runtime; generated by start.sh.
Object.assign(window.SUPABASE_CONFIG ||= {}, {
  workerUrl: "${PUBLIC_ORIGIN}/api",
});
EOF
}

case "$MODE" in
  --connected)
    if [[ -f "$FRONTEND_CONFIG" ]] && ! grep -q 'Resume Agent public cloud runtime' "$FRONTEND_CONFIG"; then
      echo "检测到自有 Supabase 配置，请运行 ./dev.sh --local 启动本地 Worker。"
      exit 2
    fi
    download_public_config
    URL="http://${HOST}:${PORT}/index.html"
    MODE_TITLE="完整云端体验"
    MODE_DESC="真实上传、解析、评分、出题与 Checker 均已启用"
    ;;
  --demo)
    URL="http://${HOST}:${PORT}/index.html?demo=1"
    MODE_TITLE="离线静态演示"
    MODE_DESC="不调用云端服务，仅展示预制结果"
    ;;
  *)
    echo "用法：./start.sh [--connected|--demo]"
    exit 2
    ;;
esac

echo
echo "=========================================="
echo "  简历中台 · ${MODE_TITLE}"
echo "  打开：${URL}"
echo "  ${MODE_DESC}"
echo "  按 Ctrl+C 停止服务"
echo "=========================================="
echo

if [[ "${NO_OPEN:-0}" != "1" ]]; then
  if command -v open >/dev/null 2>&1; then
    (sleep 0.5; open "$URL") >/dev/null 2>&1 &
  elif command -v xdg-open >/dev/null 2>&1; then
    (sleep 0.5; xdg-open "$URL") >/dev/null 2>&1 &
  fi
fi

cd "$ROOT"
python3 -m http.server "$PORT" --bind "$HOST"
